{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "check-in-bot.secretName" . }}
  labels:
    {{- include "check-in-bot.labels" . | nindent 4 }}
type: Opaque
stringData:
  CHECKIN_TOKEN: {{ required "secret.telegramToken is required when secret.create=true" .Values.secret.telegramToken | quote }}
{{- end }}
